# train_yolo.py 실행 명령어
# python scripts/train_yolo.py --config configs/train_yolo_exp1.yaml

model: model/yolo12n.pt
train:
  epochs: 200
  imgsz: 640
  batch: 8
  device: 5
  optimizer: AdamW
  lr0: 1.0e-3
  weight_decay: 1.0e-4
  scheduler: Cosine
  seed: 42
  project: yolo_exp/  # 저장될 기본 폴더
  name: yolo12n_laboro_exp1  # 실험 이름
data:
  data_yaml: /home/kdy12/tomatovision_pipeline/data/tomato_data/laboro-tomato/data.yaml