# train_yolo.py 실행 명령어 (튜닝 모드)
# python scripts/train_yolo.py --config configs/train_yolo_tune.yaml

# 1. 실행 모드 지정 (필수)
mode: tune

# 2. 모델 (기존과 동일)
model: model/yolo12n.pt

# 3. 데이터 (기존과 동일)
data:
  data_yaml: /home/kdy12/tomatovision_pipeline/data/tomato_data/laboro-tomato/data.yaml

# 4. 튜닝 설정
tune:
  # [핵심] 튜닝 시도 횟수 
  iterations: 100
  
  # [핵심] 튜닝 1회당 학습할 에포크 
  epochs: 50
  
  # 튜닝 중 고정할 값들 (학습 설정과 달라도 됨)
  imgsz: 640
  batch: 64     # GPU 메모리가 허용하는 최대치
  optimizer: AdamW  # 튜닝 알고리즘이 사용할 기본 옵티마이저
  device: 6     # 튜닝을 실행할 GPU
  
  # 튜닝 결과 저장 경로
  project: yolo_exp/
  name: yolo12n_laboro_tune3
  
  # 기타 튜닝 옵션
  plots: true    # 튜닝 결과 차트 저장
  save: true    # 최적 모델/하이퍼파라미터 저장
  val: true

